### ISSUE TITLE
iOS 12+ getConnectedSSID() and getConnectedBSSID() not working

### ISSUE THREAD

**Issue by sercandumansiz** [tripflex/WifiWizard2#60] opened 2018-11-27 15:13 UTC
### Prerequisites

Check all boxes if you have done the following:
- [x ] Checked that your issue isn't already filed: https://github.com/tripflex/wifiwizard2/issues
- [x ] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [x] Bug
- [ ] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description

Everything is fine on iOS11 but when I open the same .ipa in iOS12 device getConnectedSSID() and getConnectedBSSID() are not working. And also everything is fine on Android.

### Steps to Reproduce

**Expected behavior:** It should returns connected wi-fi's ssid and bssid

**Actual behavior:** It returns undefined on iOS12

### Versions

iOS12+

**Comment by IOOOTAlan** [comment] 2018-11-30 09:46
:+1:

**Comment by luisAzcuaga** [comment] 2018-12-03 18:40
Tried to reproduce issue with no success. What kind of iDevice are you using?
I tested it on an iPhone SE (iOS 12.1)

**Comment by IOOOTAlan** [comment] 2018-12-04 08:58
@luisAzcuaga we tried it on an iPhone 6+ -- iOS 12.0.1.

**Comment by luisAzcuaga** [comment] 2018-12-04 21:16
Today I noticed something really weird. If I download our app from the App Store, the "getConnectedSSID" part works, but if I recompile the, It won't do anything. 😨 
Both test (app store and recompilation) on the same iPhone SE -- iOS 12.1

**Comment by luisAzcuaga** [comment] 2018-12-04 22:41
I confirm, It's not working on iOS 12.1. @IOOOTAlan Can't understand why old compile works haha.

@tripflex 

![captura de pantalla 2018-12-04 a la s 16 41 07](https://user-images.githubusercontent.com/37643667/49477744-72c5c280-f7e3-11e8-858f-2d6d248cfe75.png)
![captura de pantalla 2018-12-04 a la s 16 40 34](https://user-images.githubusercontent.com/37643667/49477746-75281c80-f7e3-11e8-98d6-ef74134c0cb6.png)

**Comment by mogupta** [comment] 2018-12-13 09:07
any resolution ?

**Comment by luisAzcuaga** [comment] 2018-12-13 22:58
Nothing yet. I tried to fork the repo, but I have no experience on Swift :sweat:

**Comment by kalicki** [comment] 2018-12-20 12:57
@jack828, @saoron, @arsenal942 Did you have this problem?

**Comment by luisAzcuaga** [comment] 2018-12-28 18:31
Thanks a lot @kalicki this fixed my issue! Actually I think only the `Access WIFI Information` did the trick. Altho I had to ask the admin to change the App ID capabilities.

**Comment by tripflex** [comment] 2019-02-07 20:48
I merged a PR from @sarpherviz to add docs to README for iOS 12+ to tell users to enable that, can I go ahead and close this issue then?

I don't have any experience with the iOS stuff so based on what everyone is saying it sounds like this is something that has to be set outside of this lib, but if there is some way to define it in the lib i'm certainly open to any PRs to add this

**Comment by tripflex** [comment] 2019-02-07 21:06
@sercandumansiz @luisAzcuaga @IOOOTAlan @kalicki @mogupta  looking at this PR it looks like there's a possible way (and this may actually be it):
https://github.com/tripflex/WifiWizard2/pull/56

So are you guys using the npm version of the plugin or are you using the github version?  Can anybody try the github version and see if they still need to have this manually set?

That PR above should add this, but it has not been released to npm yet 

Details on how to use github version can be found in readme:
https://github.com/tripflex/WifiWizard2#installation

**Comment by luisAzcuaga** [comment] 2019-02-13 00:05
I actually used `cordova plugin add https://github.com/tripflex/wifiwizard2` when I installed the plugin. Didn't installed via npm. I'll give it a check @tripflex

**Comment by luisAzcuaga** [comment] 2019-02-13 00:24
I reinstalled as mentioned above and I still need to enable the Capability. @tripflex

**Comment by tripflex** [comment] 2019-02-18 20:14
@luisAzcuaga okay thank you for confirming this, I was able to get my hands on an iPhone and i'll try testing this myself soon as well, thanks again for helping test this!

**Comment by 13546777510** [comment] 2019-02-24 06:44
@luisAzcuaga  I confirm too, It's not working on iOS 12.1. The premise is that I have enabled wifi permissions. It does not enter this function/method, and there is no information output in the console.
![image](https://user-images.githubusercontent.com/20255750/53295998-ce7f7500-3841-11e9-941e-785ab1bf0f09.png)
![image](https://user-images.githubusercontent.com/20255750/53296002-e22adb80-3841-11e9-929f-3249dc53fcde.png)
![image](https://user-images.githubusercontent.com/20255750/53296031-6c733f80-3842-11e9-9f1a-39df1a1d52d9.png)
Thanks for providing a good plugin, but it seems to have a little problem

**Comment by sarpherviz** [comment] 2019-03-05 07:32
IOS12+ Distribution Certificate Not Available problem solved.

When i run the app in development certificate or adhoc certificate the application is working but when i sign the app with "Distribution Certificate" getConnectedSSID and getConnectedBSSID methods return "Not Available" error. 

After this problem platforms->ios-> "ProjectName"->Entitlements-Release.plist and Entitlements-Debug.plist files are different. I fix Entitlements-Release.plist manually and test again , i got same error.

After that i search Entitlements setting in XCODE. 

[SOLUTION]: In XCode, at Build Settings tab -> Code Signing Entitlements-> Change Release section to Entitlements-Debug.plist

Build and archive project. 

![screen shot 2019-03-05 at 10 26 57](https://user-images.githubusercontent.com/501935/53788027-9ce96680-3f31-11e9-866b-dd53613a6d71.png)

**Comment by 13546777510** [comment] 2019-03-05 08:12
@sarpherviz Thank you for your method, but I tried it and it didn't solve it. It seems that this solution seems to have nothing to do with our problem. We are not displaying the "Not Available" error, but the direct code does not enter the function, and there is no error output, and the following code will be stopped. My question still exists. I hope the official tells me how to do it. Thank you.



> @luisAzcuaga I confirm too, It's not working on iOS 12.1.2. The premise is that I have enabled wifi permissions. It does not enter this function/method, and there is no information output in the console.
> ![image](https://user-images.githubusercontent.com/20255750/53295998-ce7f7500-3841-11e9-941e-785ab1bf0f09.png)
> ![image](https://user-images.githubusercontent.com/20255750/53296002-e22adb80-3841-11e9-929f-3249dc53fcde.png)
> ![image](https://user-images.githubusercontent.com/20255750/53296031-6c733f80-3842-11e9-9f1a-39df1a1d52d9.png)
> Thanks for providing a good plugin, but it seems to have a little problem

**Comment by sarpherviz** [comment] 2019-03-07 11:58
@luisAzcuaga please check your plugin.xml file is like this? https://github.com/tripflex/WifiWizard2/blob/master/plugin.xml

**Comment by kalicki** [comment] 2019-03-13 22:25
Ping... now I have error: `Not Available` with `getConnectedSSID` 
> iOS 12.2 (compilation 16E5223a)

**Comment by luisAzcuaga** [comment] 2019-03-16 07:04
@13546777510 Hey maybe only one attempt is causing you the issue. My code is like this:

This first block is up above:
```
declare var WifiWizard2: any;
wifiInterval: any;
currentSSID: any;
```
And my method looks likes this:
```
      validateSSID() {
        this.wifiInterval = setInterval(() => {
          WifiWizard2.getConnectedSSID().then((ssid) => {
            this.currentSSID = ssid;
            console.log(this.currentSSID);
            }
          })
          .catch((err) => console.error(err));
        }, 2000);
      }
```
Hope this helps you out!

**Comment by luisAzcuaga** [comment] 2019-03-16 07:06
@kalicki This happened to me when I had the `Access Wifi Information` under the Capability section turned off. Check this comment -> https://github.com/tripflex/WifiWizard2/issues/60#issuecomment-448990878

**Comment by 13546777510** [comment] 2019-03-16 16:21
@luisAzcuaga 
Thank you for your reply, just now, I tried the code. The frustrating thing is that it still won't execute.
The system version of the phone is ios 12.1.2. These problems only appear on the iOS device. It is perfect to run on the Android 8.1 phone.
The wifi interval is always executed, but it still does not enter the WifiWizard2.getConnectedSSID() method in the wifi interval, and there is no return information.
When the code that is executed with WifiWizard2.getConnectedSSID() is included in the wifi interval, it looks like this:
```
getWifiSsid( ){
  this.wifiInterval = setInterval(()=>{
    Console.log("a");
    WifiWizard2.getConnectedSSID().xxxxx
    Console.log("b");
  }, 2000)
}
```
"a" is output every 2 seconds, and WifiWizard2.getConnectedSSID() is not executed, and "b" seems to have not been executed yet.
I have been following this problem, I will always pay attention to anyone's discussion about this issue.

In addition, here is the code block for my test, and the output of the console in Xcode：
my code:
```
//Get the ssid information of WiFi
doGetWifiSsid() {
  console.log("Ready to get WiFi ssid information");
  this.wifiInterval = setInterval(() => {
    console.log("WifiInterval is automatically refreshing WiFi information");
    WifiWizard2.getConnectedSSID().then((ssid) => {
      console.log("Get success: " + ssid);
    }).catch((err) => {
      console.log("Get failed, please check the error ↓");
      console.error(err);
    });
    console.log("Within the interval: The code was successfully executed here...");
  },2000);
  console.log("The code was successfully executed here...");
}
```
Information output from the console in Xcode：
```
2019-03-16 23:45:00.702403+0800 RisunHome[7295:2180156] Ready to get WiFi ssid information
2019-03-16 23:45:00.703685+0800 RisunHome[7295:2180156] The code was successfully executed here...
2019-03-16 23:45:02.712364+0800 RisunHome[7295:2180156] WifiInterval is automatically refreshing WiFi information
2019-03-16 23:45:04.710915+0800 RisunHome[7295:2180156] WifiInterval is automatically refreshing WiFi information
2019-03-16 23:45:06.713869+0800 RisunHome[7295:2180156] WifiInterval is automatically refreshing WiFi information
2019-03-16 23:45:08.714793+0800 RisunHome[7295:2180156] WifiInterval is automatically refreshing WiFi information
2019-03-16 23:45:10.710385+0800 RisunHome[7295:2180156] WifiInterval is automatically refreshing WiFi information
```
@tripflex @saoron @jack828 @sarpherviz @xLarry @surajrao 
This problem has always existed, calling everyone's support.

**Comment by luisAzcuaga** [comment] 2019-03-16 16:44
> @luisAzcuaga please check your plugin.xml file is like this? https://github.com/tripflex/WifiWizard2/blob/master/plugin.xml

First of all, sorry for the late response.
Now, I've checked the files and there is indeed a difference!
Weird thing is that I have less stuff on the plugin.xml
```
        <!-- Add HotspotConfiguration & NetworkExtension Capabilities  -->
        <config-file parent="com.apple.developer.networking.HotspotConfiguration" target="*/Entitlements-Debug.plist">
            <true/>
        </config-file>
        <config-file parent="com.apple.developer.networking.HotspotConfiguration" target="*/Entitlements-Release.plist">
                 <true/>
        </config-file>
        <config-file parent="com.apple.developer.networking.networkextension" target="*/Entitlements-Debug.plist">
                <array/>
        </config-file>
        <config-file parent="com.apple.developer.networking.networkextension" target="*/Entitlements-Release.plist">
                <array/>
        </config-file>
```
The one on gitlab:
```
        <!-- Add HotspotConfiguration & NetworkExtension Capabilities  -->
        <config-file parent="com.apple.developer.networking.HotspotConfiguration" target="*/Entitlements-Debug.plist">
            <true/>
        </config-file>
        <config-file parent="com.apple.developer.networking.HotspotConfiguration" target="*/Entitlements-Release.plist">
                 <true/>
        </config-file>
        <config-file parent="com.apple.developer.networking.networkextension" target="*/Entitlements-Debug.plist">
                <array/>
        </config-file>
        <config-file parent="com.apple.developer.networking.networkextension" target="*/Entitlements-Release.plist">
                <array/>
        </config-file>
	<config-file parent="com.apple.developer.networking.wifi-info" target="*/Entitlements-Debug.plist">
                <true/>
        </config-file>
        <config-file parent="com.apple.developer.networking.wifi-info" target="*/Entitlements-Release.plist">
                <true/>
        </config-file>
```

**Comment by luisAzcuaga** [comment] 2019-03-16 16:57
@13546777510 How did you installed the plugin? And what version do you have?
This is the way I did it, 
https://github.com/tripflex/WifiWizard2/issues/60#issuecomment-462996031
`cordova plugin add https://github.com/tripflex/wifiwizard2`

You'll notice this is a Linux machine, when I compile iOS I use a macbook, but the used versions are exactly the same.
__I've just installed the iOS platform on this machine so you can see the Cordova Platform version it installs.__
This are all the info versions I can get right now:
```
cli packages: (/home/luis/Code/projects/ionic-app/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 7.1.4 browser 5.0.4 ios 4.5.5
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v10.15.0
    npm               : 6.8.0 
    OS                : Linux 4.9

Environment Variables:

    ANDROID_HOME : /home/luis/Android/Sdk

Misc:

    backend : pro
```

**Comment by 13546777510** [comment] 2019-03-16 17:10
@luisAzcuaga 
This plugin seems to be installed via npm, not directly from github. I am not sure, because now I am not in front of the computer, I will reply you within the last 12 hours about the specific plugin installation and version information.
But what puzzles me is why the Android phone will run successfully, and Apple can't.
Thank you very much for your prompt reply.

**Comment by 13546777510** [comment] 2019-03-18 03:46
@luisAzcuaga 
Thank you for your reminder, I found the reason for the problem.

I executed the `ionic cordova plugin add https://github.com/tripflex/WifiWizard2.git` again, then recompiled it into ios again, and everything is fine.

I saw that it added a plugin package called `WifiWizard2` in the "Project" > "plugins" directory, and I don't know why the previous directory does not exist. Previously `WifiWizard2` only existed in "node_modules", probably what happened to me when I executed the `ionic cordova prepare ios` command.

Everything is my fault, I thought it was a plugin problem.

**Comment by luisAzcuaga** [comment] 2019-03-18 06:05
@13546777510 I'm glad is working now!

**Comment by dilip907** [comment] 2019-09-18 19:24
Hi Team,
I have tried connect with iOS 12.4 iPhone se and 6 but its always return fail.

I used those library
https://github.com/lou-lan/SmartConfig
https://github.com/EspressifApp/EsptouchForIOS/
Getting response every time
[isSuc: NO,isCancelled: NO,bssid: (null),inetAddress: (null)]

Could you please help me what I am doing wrong.

I am using same
func executeForResult() -> ESPTouchResult {
// 同步锁
condition.lock()
// 获得配置所需要的参数
esptouchTask = ESPTouchTask(apSsid: SSID, andApBssid: BSSID, andApPwd: PASS)
// 设置代理
esptouchTask.setEsptouchDelegate(esptouchDelegate)
condition.unlock()
let esptouchResult: ESPTouchResult = self.esptouchTask.executeForResult()
print("⭕️(esptouchResult)")
return esptouchResult
}

Output :-
[isSuc: NO,isCancelled: NO,bssid: (null),inetAddress: (null)]

Thanks

**Closed** 2022-04-06 20:51 UTC
Labels: User Question, Working
